# This is a collection of useful CMake functions

function(set_option_if_not_set var_name desc default)
	if (NOT DEFINED ${var_name})
		set(init_val ${default})
	else()
		set(init_val ${${var_name}})
	endif()
	option(${var_name} ${desc} ${init_val})
endfunction(set_option_if_not_set)

include(CheckCXXCompilerFlag)
include(CheckCCompilerFlag)
macro(add_supported_c_flags flag)
	string(REPLACE "=" "__" var_name c_flag_${flag})
	check_c_compiler_flag(${flag} ${var_name})
	if (${var_name})
		set(TYPECHECK_EXTRA_FLAGS ${TYPECHECK_EXTRA_FLAGS} ${flag})
	endif()
endmacro()

macro(add_supported_cxx_flags flag)
 	string(REPLACE "=" "__" var_name cxx_flag_${flag})
    check_cxx_compiler_flag(${flag} ${var_name})
    if (${var_name})
    	set(TYPECHECK_EXTRA_FLAGS ${TYPECHECK_EXTRA_FLAGS} ${flag})
    else()
    	add_supported_c_flags(${flag})
    endif()
endmacro()
